# Generated by Django 5.1.7 on 2025-07-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_helparticle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="helparticle",
            name="created_by",
        ),
        migrations.DeleteModel(
            name="APIKey",
        ),
        migrations.DeleteModel(
            name="HelpArticle",
        ),
    ]
