# Generated by Django 5.1.7 on 2025-08-07 14:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_mfa_backup_email_customuser_mfa_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="mfa_enforced_at",
            field=models.DateTimeField(
                blank=True, help_text="When MFA was enforced for this user", null=True
            ),
        ),
        migrations.CreateModel(
            name="MFAEnforcementLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("warning_sent", "Warning Email Sent"),
                            ("access_restricted", "Access Restricted"),
                            ("mfa_setup_completed", "MFA Setup Completed"),
                            ("enforcement_bypassed", "Enforcement Bypassed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mfa_actions_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_enforcement_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
