# Generated by Django 5.1.7 on 2025-08-07 16:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_customuser_mfa_enforced_at_mfaenforcementlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mfaenforcementlog",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="mfaenforcementlog",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="recoverycode",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="recoverycode",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="trusteddevice",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="trusteddevice",
            name="user",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="mfa_enabled",
            new_name="two_factor_enabled",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mfa_backup_email",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mfa_enforced_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="mfa_method",
        ),
        migrations.AddField(
            model_name="customuser",
            name="backup_tokens_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_enforced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When 2FA enforcement started for this user",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="two_factor_grace_period_ends",
            field=models.DateTimeField(
                blank=True, help_text="When the 14-day grace period ends", null=True
            ),
        ),
        migrations.AddField(
            model_name="loginattempt",
            name="two_factor_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("totp", "TOTP App"),
                    ("email", "Email Code"),
                    ("backup", "Backup Code"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loginattempt",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("blocked", "Blocked"),
                    ("2fa_required", "2FA Required"),
                    ("2fa_success", "2FA Success"),
                    ("2fa_failed", "2FA Failed"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TwoFactorBackupToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=255, unique=True)),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="backup_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwoFactorEmailToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_2fa_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="EmailMFAToken",
        ),
        migrations.DeleteModel(
            name="MFAEnforcementLog",
        ),
        migrations.DeleteModel(
            name="RecoveryCode",
        ),
        migrations.DeleteModel(
            name="TrustedDevice",
        ),
    ]
