# Generated by Django 5.1.7 on 2025-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="bitrate",
            field=models.PositiveIntegerField(
                blank=True, help_text="Bitrate in kbps (optional)", null=True
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="connection_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("ok", "OK"),
                    ("unauthorized", "Unauthorized"),
                    ("unreachable", "Unreachable"),
                    ("error", "Error"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("mp3", "MP3"), ("aac", "AAC/AAC+"), ("ogg", "Ogg Vorbis")],
                help_text="Audio format (optional)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="host",
            field=models.CharField(
                blank=True,
                help_text="Hostname or IP of your streaming server",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="last_tested_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="station",
            name="password",
            field=models.CharField(
                blank=True,
                help_text="Optional password if your stream requires HTTP auth",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="port",
            field=models.PositiveIntegerField(default=8000, help_text="Server port"),
        ),
        migrations.AddField(
            model_name="station",
            name="protocol",
            field=models.CharField(
                choices=[("http", "http"), ("https", "https")],
                default="http",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Optional username if your stream requires HTTP auth",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="mount",
            field=models.CharField(
                blank=True,
                help_text="Mountpoint (e.g., /stream) for Icecast or path segment",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="station",
            name="url",
            field=models.URLField(blank=True),
        ),
    ]
