# Generated by Django 5.1.7 on 2025-08-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcasts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="enable_radio",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="enable_youtube",
            field=models.BooleanField(default=False),
        ),
    ]
