# Generated by Django 5.1.7 on 2025-08-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broadcasts", "0002_broadcast_enable_radio_broadcast_enable_youtube"),
        ("stations", "0002_station_bitrate_station_connection_status_and_more"),
        ("youtube_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="broadcast",
            name="stations",
            field=models.ManyToManyField(
                blank=True, related_name="broadcasts", to="stations.station"
            ),
        ),
        migrations.AddField(
            model_name="broadcast",
            name="youtube_channels",
            field=models.ManyToManyField(
                blank=True,
                related_name="broadcasts",
                to="youtube_integration.youtubechannel",
            ),
        ),
    ]
